import type { Metadata } from "next";
import { Russo_One } from "next/font/google";
import "./globals.css";

const russoOne = Russo_One({
  variable : "--font-main",
  weight: "400",
  subsets : ["latin"]
})

export const metadata: Metadata = {
  title: "Badminton Score",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
    apple: "/logo.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${russoOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
