import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from "next";
import { Russo_One, Tinos } from "next/font/google";
import "./globals.css";

const russoOne = Russo_One({
  variable: "--font-main",
  weight: "400",
  subsets: ["latin"],
});

const tinos = Tinos({
  variable: "--font-secondary",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Badminton Score",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-white.svg",
    apple: "/logo-white.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${russoOne.variable} ${tinos.variable} antialiased`}>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
